#!/usr/bin/env node
/**
 * Non-interactive equivalent of `bubblewrap init` — calls the same
 * @bubblewrap/core library `init` itself uses, but supplies every answer
 * as a value instead of an interactive prompt (this tool's shell can't
 * drive bubblewrap's own inquirer-based prompts reliably). Safe to
 * re-run: TwaGenerator.createTwaProject() overwrites the generated
 * project files but createSigningKey() leaves an existing keystore
 * alone.
 */
import { resolve, join } from "node:path";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { TwaManifest, TwaGenerator, JdkHelper, KeyTool, BufferedLog, ConsoleLog } from "@bubblewrap/core";

const targetDirectory = resolve(process.cwd());
const manifestUrl = "https://orders.ronmacraedistributions.com/manifest.webmanifest";

const config = {
  jdkPath: "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk",
  androidSdkPath: "/opt/homebrew/share/android-commandlinetools",
};

let twaManifest = await TwaManifest.fromWebManifest(manifestUrl);

// --- Android app details (bubblewrap init's "Step 2/5") ---
// Play Console created the app listing under this exact applicationId —
// it must match precisely, and it's unrelated to the actual web domain
// (hostName below stays orders.ronmacraedistributions.com regardless;
// the Android package id is purely a store-listing identity, not
// something the web app's own login/API/OTP logic reads or depends on).
twaManifest.packageId = "com.login.dispatched";
twaManifest.launcherName = "Dispatch"; // max 12 chars
// First build under this (new, never-before-uploaded) package id — 1 is
// the correct starting versionCode, not a bump off the old package's
// history, which doesn't carry over to a different applicationId.
twaManifest.appVersionCode = 1;
twaManifest.appVersionName = "1";
twaManifest.orientation = "portrait";
// name/display/themeColor/backgroundColor/iconUrl/maskableIconUrl all
// came from the live manifest.webmanifest already (Step 1 + 3 defaults).

// Same existing production keystore and key alias — the alias name is
// baked into that keystore file's own entry and must stay exactly what
// it already is regardless of the app's package id, or signing will
// fail against the real key.
twaManifest.signingKey.path = join(targetDirectory, "android-keystore");
twaManifest.signingKey.alias = "ronmacrae-dispatch";
twaManifest.generatorApp = "@bubblewrap/cli";

await twaManifest.saveToFile(join(targetDirectory, "twa-manifest.json"));

const twaGenerator = new TwaGenerator();
const log = new BufferedLog(new ConsoleLog("Generating TWA"));
await twaGenerator.createTwaProject(targetDirectory, twaManifest, log, () => {});
log.flush();

// manifest-checksum.txt — lets a future `bubblewrap update` detect that
// the live web manifest changed since this project was generated.
const manifestContents = readFileSync(join(targetDirectory, "twa-manifest.json"));
const { createHash } = await import("node:crypto");
writeFileSync(join(targetDirectory, "manifest-checksum.txt"), createHash("sha256").update(manifestContents).digest("hex"));

// --- Signing key (bubblewrap init's "Step 5/5") ---
// This is the *upload key* Play Console will ask for on first submission
// (Play App Signing then generates and holds the real distribution key
// itself — the standard, Google-recommended flow, and the only sane one
// for a key that must never be lost). Real secret: written only to this
// gitignored directory, never printed to logs, never committed.
//
// Generated together, gated by the SAME existence check KeyTool.
// createSigningKey() already applies to the keystore file itself — writing
// a fresh credentials file next to an untouched pre-existing keystore
// would silently orphan it with a password that doesn't open it (this
// happened once while building this script; keeping the guard here is
// what makes a re-run actually safe, not just documented as safe).
if (existsSync(twaManifest.signingKey.path)) {
  console.log("[generate-project] android-keystore already exists — leaving it (and keystore-credentials.txt) untouched.");
} else {
  const keystorePassword = randomBytes(18).toString("base64url");
  const keyPassword = keystorePassword; // one secret to track, not two
  writeFileSync(join(targetDirectory, "keystore-credentials.txt"), [
    "# ronmacrae-dispatch Android upload-key credentials",
    "# Generated by android/generate-project.mjs — back this up somewhere safe",
    "# (a password manager, not just this file) and never commit it or share it publicly.",
    "# Losing it means you can no longer sign updates to this exact app listing without",
    "# Google's Play App Signing key-upgrade/recovery process.",
    "",
    `keystore_path=${join(targetDirectory, "android-keystore")}`,
    "key_alias=ronmacrae-dispatch",
    `keystore_password=${keystorePassword}`,
    `key_password=${keyPassword}`,
    "",
  ].join("\n"));

  const jdkHelper = new JdkHelper(process, config);
  const keytool = new KeyTool(jdkHelper);
  await keytool.createSigningKey({
    fullName: "Ronmacrae Distributions",
    organizationalUnit: "Dispatch",
    organization: "Ronmacrae Distributions",
    country: "JM",
    password: keystorePassword,
    keypassword: keyPassword,
    alias: twaManifest.signingKey.alias,
    path: twaManifest.signingKey.path,
  });
}

console.log("\n[generate-project] done — TWA project + signing key generated in", targetDirectory);
